# Generated by Django 4.2.7 on 2025-07-08 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scan_type', models.CharField(choices=[('git_url', 'Git URL'), ('zip_upload', 'ZIP Upload')], max_length=20)),
                ('repository_url', models.URLField(blank=True, null=True)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_files_scanned', models.IntegerField(default=0)),
                ('secrets_found', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SecretFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('line_number', models.IntegerField()),
                ('secret_type', models.CharField(choices=[('aws_key', 'AWS Access Key'), ('aws_secret', 'AWS Secret Key'), ('gcp_key', 'GCP Service Account Key'), ('jwt_token', 'JWT Token'), ('db_url', 'Database URL'), ('email_password', 'Email/Password'), ('private_key', 'Private Key'), ('api_key', 'API Key'), ('oauth_token', 'OAuth Token'), ('ssh_key', 'SSH Key')], max_length=50)),
                ('severity', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('matched_text', models.TextField()),
                ('context_before', models.TextField(blank=True)),
                ('context_after', models.TextField(blank=True)),
                ('is_false_positive', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('scan_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='scanner.scansession')),
            ],
            options={
                'ordering': ['-severity', 'file_path', 'line_number'],
            },
        ),
    ]
