# Generated by Django 4.2.7 on 2025-07-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scansession',
            name='auto_remediation',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
