# Generated by Django 4.2.7 on 2025-07-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_scansession_auto_remediation'),
    ]

    operations = [
        migrations.AddField(
            model_name='scansession',
            name='commits_scanned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scansession',
            name='is_deep_scan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='secretfinding',
            name='commit_author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='secretfinding',
            name='commit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='secretfinding',
            name='commit_hash',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='secretfinding',
            name='commit_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scansession',
            name='scan_type',
            field=models.CharField(choices=[('git_url', 'Git URL'), ('zip_upload', 'ZIP Upload'), ('git_deep', 'Git Deep Scan')], max_length=20),
        ),
    ]
